"""initial tables

Revision ID: 91977a1d12d2
Revises: 
Create Date: 2025-09-05 19:05:50.931661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.infrastructure.db.migration_helpers.triggers import (
    create_triggers, drop_triggers,
)

# revision identifiers, used by Alembic.
revision: str = '91977a1d12d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk__categories__parent_id__categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categories')),
    sa.UniqueConstraint('parent_id', 'name', name='uq__categories__parent_name')
    )
    op.create_index('ix__categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix__categories_parent_id', 'categories', ['parent_id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__clients')),
    sa.UniqueConstraint('name', name=op.f('uq__clients__name'))
    )

    op.create_table('category_trees',
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['categories.id'], name=op.f('fk__category_trees__ancestor_id__categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['categories.id'], name=op.f('fk__category_trees__descendant_id__categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id', name=op.f('pk__category_trees'))
    )
    op.create_index('ix__cc_ancestor', 'category_trees', ['ancestor_id'], unique=False)
    op.create_index('ix__cc_descendant', 'category_trees', ['descendant_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk__orders__client_id__clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__orders'))
    )
    op.create_index('ix__orders_client_id', 'orders', ['client_id'], unique=False)
    op.create_index('ix__orders_create_date', 'orders', ['create_date'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__products__category_id__categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products')),
    sa.UniqueConstraint('category_id', 'name', name='uq__products_category_name_model')
    )
    op.create_index('ix__products_category_id', 'products', ['category_id'], unique=False)

    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk__order_items__order_id__orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk__order_items__product_id__products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk__order_items'))
    )
    op.create_index('ix__order_items_product', 'order_items', ['product_id'], unique=False)

    create_triggers()
    # ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__order_items_product', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix__products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix__orders_created_at', table_name='orders')
    op.drop_index('ix__orders_client_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix__cc_descendant', table_name='category_trees')
    op.drop_index('ix__cc_ancestor', table_name='category_trees')
    op.drop_table('category_trees')
    op.drop_table('clients')
    op.drop_index('ix__categories_parent_id', table_name='categories')
    op.drop_index('ix__categories_name', table_name='categories')
    op.drop_table('categories')

    drop_triggers()
    # ### end Alembic commands ###
